# Generated by Django 5.2.5 on 2025-08-18 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Collection',
        ),
    ]
