# Generated by Django 5.2.5 on 2025-08-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_delete_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
